import Head from "next/head";
import Image from "next/image";
import { Poppins } from "next/font/google";
import { useState, useRef } from "react";
import React from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import axios from "axios";
import ReactLoading from "react-loading";
import SegmentedControl from "@/components/SegmentedControl";
import Rewrite from "../public/rewrite.svg";
import toast, { Toaster } from "react-hot-toast";

const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export default function Home() {
  const [length, setLength] = useState("short");
  const [type, setType] = useState("Casual");
  const [sentence, setSentence] = useState<any>("");
  const [input, setInput] = useState("");
  const [isLoading, setIsloading] = useState<boolean>(false);

  const prompt = `rewrite the following "${input}", make sure to keep the same meaning, ${
    type === "Casual"
      ? "and make sure to make it look Casual"
      : "and make sure to make it look formal"
  }, ${
    length === "short"
      ? "and make sure to make the sentence look shorter"
      : null
  }`;

  const copy = async () => {
    await navigator.clipboard.writeText(sentence);
    toast("Copied to clipboard", {
      icon: "👏",
    });
  };

  // const submit = async () => {
  //   setIsloading(true);
  //   axios
  //     .post("/api/sentence-rephraser", {
  //       prompt: prompt,
  //     })
  //     .then(function (res: any) {
  //       setIsloading(false);
  //       setSentence(res.data);
  //       console.log(res);
  //     })
  //     .catch(function (err: any) {
  //       console.log(err);
  //     });
  // };

  const submit = async (e?: any) => {
    setSentence("");
    setIsloading(true);
    const response = await fetch("/api/sentence-rephraser", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        prompt,
      }),
    });

    if (!response.ok) {
      throw new Error(response.statusText);
    }

    // This data is a ReadableStream
    const data = response.body;
    if (!data) {
      return;
    }

    const reader = data.getReader();
    const decoder = new TextDecoder();
    let done = false;

    while (!done) {
      const { value, done: doneReading } = await reader.read();
      done = doneReading;
      const chunkValue = decoder.decode(value);
      setSentence((prev: string) => prev + chunkValue);
    }
    setIsloading(false);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:title" content="Sentence Rephraser" />
        <meta
          property="og:description"
          content="Improve your writing with ChatGPT, a cutting-edge language model that offers personalized writing suggestions, grammatical corrections, and vocabulary expansion in real-time. Use it as a writing assistant or for generating ideas, and it can handle a variety of writing styles and genres. Sign up now to take your writing skills to the next level."
        />
        <meta name="twitter:card" content="summary_large_image"></meta>
        <meta
          property="og:image"
          content="https://media.discordapp.net/attachments/863411239668940800/1084054389074972772/sen-ref.png?width=1984&height=820"
        />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <div className="App">
          <Toaster
            toastOptions={{
              style: {
                padding: "12px 24px",
                color: "#0D0D0D",
                background: "#fff",
              },
            }}
          />
          <Navbar />
          <div className="flex flex-col gap-6 items-center w-128 sm:w-10/12">
            <h1 className="flex flex-col gap-6 text-center leading-11 font-bold text-5xl sm:text-4xl">
              Boost your writing using chatGPT
            </h1>
            <div className="flex flex-col w-full gap-2 mt-4">
              <SegmentedControl
                name="group-2"
                callback={(val: string) => setType(val)}
                controlRef={useRef()}
                defaultIndex={0}
                segments={[
                  {
                    label: "Casual",
                    value: "Casual",
                    ref: useRef(),
                  },
                  {
                    label: "Formal",
                    value: "Formal",
                    ref: useRef(),
                  },
                ]}
              />
              <textarea
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => {
                  e.key === "Enter" ? submit() : null;
                }}
                className="input placeholder-grey-60 sm:placeholder:text-sm"
                rows={3}
                placeholder="Hello World."
              ></textarea>
              <button
                onClick={() => {
                  submit();
                }}
                className="flex flex-row justify-center items-center gap-1 sm:text-sm"
              >
                {isLoading ? (
                  <ReactLoading
                    width="24px"
                    height="24px"
                    type="bubbles"
                    color="#0D0D0D"
                  />
                ) : (
                  <>
                    <Image src={Rewrite} alt="hi" /> Rewrite
                  </>
                )}{" "}
              </button>
            </div>
            {sentence ? (
              <div
                onClick={copy}
                className="cursor-copy inline-block w-full bg-grey-90 p-4 border-solid border-2 border-grey-80 rounded-lg mt-4 mb-8 sm:max-w-10/12 sm:text-sm"
              >
                <p className="max-w-auto m-auto">{sentence}</p>
                {/* {sentence} */}
              </div>
            ) : null}
            {/* <div className="flex text-center bg-grey-90 p-4 max-w-4/6 border-solid border-2 border-grey-80 rounded-lg mt-4">
              {sentence}
            </div> */}
          </div>
          <Footer />
        </div>
      </main>
    </>
  );
}
